name: Update Badges

on:
  push:
    branches: [ main ]
  schedule:
    # Update badges daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Generate coverage report
      run: |
        pytest --cov=pitwall --cov-report=json

    - name: Extract coverage percentage
      id: coverage
      run: |
        export COVERAGE=$(python -c "import json; print(json.load(open('coverage.json'))['totals']['percent_covered_display'])")
        echo "percentage=$COVERAGE" >> $GITHUB_OUTPUT

    - name: Create coverage badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GITHUB_TOKEN }}
        gistID: ${{ secrets.COVERAGE_GIST_ID }}
        filename: pitwall-coverage.json
        label: Coverage
        message: ${{ steps.coverage.outputs.percentage }}%
        color: ${{ steps.coverage.outputs.percentage > 80 && 'brightgreen' || steps.coverage.outputs.percentage > 60 && 'yellow' || 'red' }}

    - name: Create tests badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GITHUB_TOKEN }}
        gistID: ${{ secrets.TESTS_GIST_ID }}
        filename: pitwall-tests.json
        label: Tests
        message: Passing
        color: brightgreen