name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      test-release:
        description: 'Test release to TestPyPI'
        required: false
        type: boolean
        default: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.test-release == 'true' && 'test-pypi' || 'pypi' }}
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: |
        python -m build

    - name: Publish to TestPyPI
      if: github.event.inputs.test-release == 'true'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

    - name: Publish to PyPI
      if: github.event.inputs.test-release != 'true' && github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@release/v1